name: Run the dev-install script

on:
  push:
    branches: master
  pull_request:
    branches: '*'

jobs:
  devinstall:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Cache pip on Linux
        uses: actions/cache@v3
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install notebook jupyterlab~=3.0 jupyter_packaging~=0.10
      - name: Run the dev-install script
        run: |
          ./dev-install.sh
          jupyter nbextension list
          jupyter labextension list

          python -m jupyterlab.browser_check
